import { IsolationForest } from './isolation-forest'
import { quantile } from './metrics'
import { createRng } from './random'
import { generateNominal, toFeatureVector, type TelemetrySample } from './telemetry'
import evaluationResults from './evaluation-results.json'

export type Severity = 'nominal' | 'elevated' | 'critical'

export interface DetectionOutcome {
  /** Raw Isolation Forest score in [0, 1]. */
  readonly score: number
  /** Score scaled to 0-100 for display. */
  readonly displayScore: number
  readonly severity: Severity
  /** True when the score clears the calibrated alerting threshold. */
  readonly flagged: boolean
}

/**
 * Runtime configuration. Smaller than the evaluation config so the forest
 * trains in a few hundred milliseconds on the client without blocking paint.
 */
const RUNTIME_CONFIG = {
  numTrees: 96,
  sampleSize: 256,
  trainingSamples: 2000,
  seed: 42,
  targetSpecificity: 0.99,
} as const

/** Severity bands, expressed relative to the calibrated threshold. */
const ELEVATED_FRACTION = 0.92

let cached: { forest: IsolationForest; threshold: number } | null = null

/**
 * Builds (and memoises) the detector. Training is deterministic, so every
 * client produces an identical forest and scores agree across sessions.
 */
export function getDetector(): { forest: IsolationForest; threshold: number } {
  if (cached !== null) return cached

  const rng = createRng(RUNTIME_CONFIG.seed)
  const training = Array.from({ length: RUNTIME_CONFIG.trainingSamples }, () =>
    toFeatureVector(generateNominal(rng)),
  )

  const forest = new IsolationForest({
    numTrees: RUNTIME_CONFIG.numTrees,
    sampleSize: RUNTIME_CONFIG.sampleSize,
    seed: RUNTIME_CONFIG.seed,
  }).fit(training)

  const threshold = quantile(forest.score(training), RUNTIME_CONFIG.targetSpecificity)

  cached = { forest, threshold }
  return cached
}

export function detect(sample: TelemetrySample): DetectionOutcome {
  const { forest, threshold } = getDetector()
  const score = forest.scoreOne(toFeatureVector(sample))

  const flagged = score >= threshold
  const severity: Severity = flagged
    ? 'critical'
    : score >= threshold * ELEVATED_FRACTION
      ? 'elevated'
      : 'nominal'

  return { score, displayScore: score * 100, severity, flagged }
}

/**
 * Published detector performance, generated by `npm run evaluate`.
 *
 * Read from JSON rather than written into markup, so the figures in the UI
 * always correspond to a run that actually happened.
 */
export const DETECTOR_PERFORMANCE = evaluationResults

/** Headline accuracy, formatted for display. */
export function formattedAccuracy(): string {
  return `${(DETECTOR_PERFORMANCE.overall.accuracy * 100).toFixed(1)}%`
}
