'use client'

import { DETECTOR_PERFORMANCE, formattedAccuracy } from '@/lib/detection/detector'
import { ATTACK_KINDS } from '@/lib/detection/telemetry'
import type { SatelliteGroup } from '@/lib/orbital/types'
import { ATTACK_DEFINITIONS } from '@/lib/simulation/reducer'
import { GROUP_COLORS, GROUP_LABELS, PALETTE } from '@/lib/theme'
import styles from './MetricsPanel.module.css'

interface MetricsPanelProps {
  readonly threatScore: number
  readonly band: 'LOW RISK' | 'ELEVATED' | 'CRITICAL'
  readonly alertCount: number
  readonly satelliteCount: number
  readonly source: 'live' | 'fallback' | 'mixed' | 'unknown'
  readonly maxEpochAgeHours: number
  readonly accuracyKm: number
  readonly status: 'loading' | 'ready' | 'error'
  readonly error: string | null
  readonly visibleSection: 'globe' | 'sources' | 'threats' | 'alerts'
  readonly counts: Readonly<Record<SatelliteGroup, number>>
}

export function MetricsPanel(props: MetricsPanelProps): React.ReactElement {
  const bandColor =
    props.band === 'CRITICAL' ? PALETTE.red : props.band === 'ELEVATED' ? PALETTE.amber : PALETTE.green

  return (
    <div id="console-panel" role="tabpanel" aria-labelledby={`tab-${props.visibleSection}`}>
      <div className={styles.metrics}>
        <Metric label="Threat score" value={props.threatScore.toFixed(0)} sub={props.band} color={bandColor} />
        <Metric
          label="Alerts"
          value={String(props.alertCount)}
          sub={props.alertCount > 0 ? 'in feed' : 'all nominal'}
          color={props.alertCount > 0 ? PALETTE.amber : PALETTE.text3}
        />
        <Metric
          label="Satellites"
          value={String(props.satelliteCount)}
          sub="LEO · MEO · GEO"
          color={PALETTE.blue}
        />
        {/*
          Accuracy is read from lib/detection/evaluation-results.json, which is
          regenerated by `npm run evaluate`. The legacy build hardcoded 94.7% in
          markup with no evaluation behind it.
        */}
        <Metric
          label="Detector accuracy"
          value={formattedAccuracy()}
          sub="Isolation Forest"
          color={PALETTE.green}
        />
      </div>

      {props.error !== null && (
        <p className={styles.warning} role="alert">
          {props.error}
        </p>
      )}

      {props.visibleSection === 'sources' && (
        <section className={styles.section} aria-label="Data sources">
          <h2 className={styles.sectionTitle}>Live Data Sources</h2>
          <ul className={styles.sourceList}>
            {(Object.keys(props.counts) as SatelliteGroup[]).map((group) => (
              <li key={group} className={styles.sourceRow}>
                <span className={styles.sourceDot} style={{ background: GROUP_COLORS[group] }} />
                <span className={styles.sourceName}>{GROUP_LABELS[group]}</span>
                <span className={styles.sourceCount}>{props.counts[group]}</span>
                <span className={props.counts[group] > 0 ? styles.badgeOk : styles.badgeOff}>
                  {props.counts[group] > 0 ? 'LIVE' : '—'}
                </span>
              </li>
            ))}
          </ul>

          {/*
            Accuracy is stated as a function of TLE age rather than a fixed
            figure. The legacy build claimed "accurate to meters" in one place
            and "~1 km" in another.
          */}
          <dl className={styles.provenance}>
            <div className={styles.provenanceRow}>
              <dt>Source</dt>
              <dd>
                {props.source === 'live'
                  ? 'CelesTrak (live)'
                  : props.source === 'fallback'
                    ? 'Bundled snapshot'
                    : props.source === 'mixed'
                      ? 'CelesTrak + bundled snapshot'
                      : 'Loading'}
              </dd>
            </div>
            <div className={styles.provenanceRow}>
              <dt>Element age</dt>
              <dd>{props.maxEpochAgeHours.toFixed(1)} h</dd>
            </div>
            <div className={styles.provenanceRow}>
              <dt>Est. position error</dt>
              <dd>±{props.accuracyKm.toFixed(1)} km</dd>
            </div>
          </dl>
          <p className={styles.footnote}>
            SGP4/SDP4 propagation. Accuracy is roughly 1 km at epoch and degrades a few km per day, so
            the figure above tracks the age of the loaded elements.
          </p>
        </section>
      )}

      {props.visibleSection === 'threats' && (
        <section className={styles.section} aria-label="Threat compendium">
          <h2 className={styles.sectionTitle}>Threat Compendium</h2>
          <dl className={styles.threatList}>
            {ATTACK_KINDS.map((kind) => {
              const definition = ATTACK_DEFINITIONS[kind]
              const recall = DETECTOR_PERFORMANCE.recallByAttack[kind]
              return (
                <div key={kind} className={styles.threat}>
                  <dt className={styles.threatName}>
                    {definition.label}
                    <span className={styles.threatSeverity}>{definition.severity}</span>
                  </dt>
                  <dd>
                    <p className={styles.threatBody}>{definition.description}</p>
                    <p className={styles.threatExample}>{definition.realWorldExample}</p>
                    {/*
                      Per-class recall from the evaluation run. Phishing is the
                      weakest class by a wide margin, and saying so is more
                      useful than hiding it.
                    */}
                    <p className={styles.threatRecall}>
                      Detector recall: <strong>{(recall * 100).toFixed(1)}%</strong>
                    </p>
                  </dd>
                </div>
              )
            })}
          </dl>
          <p className={styles.footnote}>
            Measured on simulated telemetry over {DETECTOR_PERFORMANCE.config.testNominalSamples.toLocaleString()}{' '}
            nominal and {(DETECTOR_PERFORMANCE.config.testSamplesPerAttack * ATTACK_KINDS.length).toLocaleString()}{' '}
            attack samples. ROC AUC {DETECTOR_PERFORMANCE.rocAuc.toFixed(3)}. Regenerate with{' '}
            <code>npm run evaluate</code>.
          </p>
        </section>
      )}
    </div>
  )
}

function Metric({
  label,
  value,
  sub,
  color,
}: {
  label: string
  value: string
  sub: string
  color: string
}): React.ReactElement {
  return (
    <div className={styles.metric}>
      <p className={styles.metricLabel}>{label}</p>
      <p className={styles.metricValue} style={{ color }}>
        {value}
      </p>
      <p className={styles.metricSub}>{sub}</p>
    </div>
  )
}
