import { expect, test, type Page } from '@playwright/test'

/**
 * Critical-path coverage for the console.
 *
 * These assert behaviours that unit tests cannot reach: that the canvas
 * actually mounts, that simulations wire through to the DOM, and — most
 * importantly — that reset genuinely clears a running phishing chain, which is
 * the defect that survived in the legacy build precisely because nothing
 * exercised it end to end.
 */

/*
 * Addressed by data-testid rather than class name: CSS module classes are
 * hashed per build, so selectors that work in dev silently miss in production.
 */
const alertItems = (page: Page) => page.getByTestId('alert-item')
const sandboxStatus = (page: Page) => page.getByTestId('sandbox-status')
const attackCounts = (page: Page) => page.getByTestId('attack-count')

async function waitForSatellites(page: Page): Promise<void> {
  await expect(page.getByRole('application')).toHaveAttribute(
    'aria-label',
    /showing [1-9]\d* tracked satellites/,
    { timeout: 30_000 },
  )
}

test.beforeEach(async ({ page }) => {
  await page.goto('/')
})

test('loads and tracks satellites', async ({ page }) => {
  await expect(page).toHaveTitle(/AEGIS/)
  await waitForSatellites(page)

  // The screen-reader summary is the text equivalent of the canvas.
  await expect(page.locator('.sr-only').first()).toContainText(/Tracking \d+ satellites/)
})

test('renders the detector accuracy generated by the evaluation harness', async ({ page }) => {
  // Must be a real percentage read from evaluation-results.json, never a
  // hardcoded marketing figure.
  await expect(page.getByText(/^\d{2}\.\d%$/).first()).toBeVisible()
  await expect(page.getByText('Isolation Forest')).toBeVisible()
})

test('exposes a keyboard-operable, labelled globe', async ({ page }) => {
  const globe = page.getByRole('application')
  await expect(globe).toBeVisible()
  await globe.focus()
  await expect(globe).toBeFocused()

  // Arrow keys must not scroll the page; the renderer consumes them.
  await page.keyboard.press('ArrowRight')
  await page.keyboard.press('ArrowUp')
  await expect(globe).toBeFocused()
})

test('tabs are real tabs with keyboard semantics', async ({ page }) => {
  const tabs = page.getByRole('tab')
  await expect(tabs).toHaveCount(4)

  const dataSources = page.getByRole('tab', { name: 'Data Sources' })
  await dataSources.click()
  await expect(dataSources).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: 'Live Data Sources' })).toBeVisible()

  await page.getByRole('tab', { name: 'Threat Types' }).click()
  await expect(page.getByRole('heading', { name: 'Threat Compendium' })).toBeVisible()
})

test('reports data provenance and an age-derived accuracy', async ({ page }) => {
  await waitForSatellites(page)
  await page.getByRole('tab', { name: 'Data Sources' }).click()

  // Accuracy is stated as a function of element age, never as a fixed claim.
  await expect(page.getByText('Est. position error')).toBeVisible()
  await expect(page.getByText(/±\d+(\.\d+)? km/)).toBeVisible()
  await expect(page.getByText('Element age')).toBeVisible()
})

test.describe('threat simulations', () => {
  test('each conventional attack produces an alert', async ({ page }) => {
    await waitForSatellites(page)

    for (const name of ['GPS Spoofing', 'Signal Jamming', 'Command Injection', 'Replay Attack']) {
      await page.getByRole('button', { name: new RegExp(name, 'i') }).first().click()
      await expect(alertItems(page).first()).toContainText(name, { timeout: 10_000 })
    }

    await expect(alertItems(page)).toHaveCount(4)
  })

  test('threat score leaves LOW RISK after a critical attack', async ({ page }) => {
    await waitForSatellites(page)
    await expect(page.getByText('LOW RISK')).toBeVisible()

    await page.getByRole('button', { name: /Command Injection/i }).first().click()

    // A lone command injection must not read as low risk.
    await expect(page.getByText('LOW RISK')).toBeHidden()
  })

  test('phishing chain advances through its stages', async ({ page }) => {
    await waitForSatellites(page)
    await page.getByRole('button', { name: /Ground Station Phishing/i }).click()

    await expect(sandboxStatus(page)).toContainText('PHISH 1/6')
    await expect(sandboxStatus(page)).toContainText('PHISH 2/6', { timeout: 10_000 })
    await expect(alertItems(page).first()).toContainText('Ground Station Phishing')
  })

  /*
   * The regression that matters most.
   *
   * In the legacy build, RESET SIMULATION left the phishing setTimeout running,
   * never zeroed the attack counters, and never cleared the threat score — so
   * alerts reappeared seconds after a "reset". This asserts the state is still
   * clean well past two further stage intervals.
   */
  test('reset clears a running phishing chain permanently', async ({ page }) => {
    await waitForSatellites(page)

    await page.getByRole('button', { name: /Ground Station Phishing/i }).click()
    await expect(alertItems(page).first()).toBeVisible()
    await expect(sandboxStatus(page)).toContainText('PHISH 2/6', { timeout: 10_000 })

    await page.getByRole('button', { name: /Reset simulation/i }).click()

    await expect(alertItems(page)).toHaveCount(0)
    await expect(sandboxStatus(page)).toContainText('STANDBY')

    // Past two more stage intervals: nothing may resurrect.
    await page.waitForTimeout(6000)
    await expect(alertItems(page)).toHaveCount(0)
    await expect(sandboxStatus(page)).toContainText('STANDBY')
    await expect(page.getByText('LOW RISK')).toBeVisible()
  })

  test('reset zeroes the attack counters', async ({ page }) => {
    await waitForSatellites(page)

    await page.getByRole('button', { name: /GPS Spoofing/i }).first().click()
    await page.getByRole('button', { name: /Signal Jamming/i }).first().click()

    const counters = attackCounts(page)
    await expect(counters.first()).not.toHaveText('0')

    await page.getByRole('button', { name: /Reset simulation/i }).click()

    const values = await counters.allTextContents()
    expect(values.every((value) => value.trim() === '0')).toBe(true)
  })
})

test('alert feed announces detections politely', async ({ page }) => {
  await waitForSatellites(page)
  const feed = page.locator('ol[aria-live="polite"]')
  await expect(feed).toBeAttached()

  await page.getByRole('button', { name: /GPS Spoofing/i }).first().click()
  // Severity is spelled out, not conveyed by colour alone.
  await expect(alertItems(page).first()).toContainText(/\[(CRITICAL|WARNING)\]/)
})
