import snapshot from './fallback-tles.json'
import { maxEpochAge } from './celestrak'
import type { SatelliteGroup, TleRecord } from './types'

/**
 * Bundled TLE snapshot, used when CelesTrak is unreachable.
 *
 * Generated by `npm run refresh:fallback` from live data, so every record has
 * valid checksums and a genuine epoch. Callers must surface `ageHours` — a
 * stale snapshot still propagates, but accuracy degrades by a few km per day
 * and the UI is expected to say so rather than quote a fixed figure.
 */

interface FallbackSnapshot {
  readonly generatedAt: string
  readonly groups: Partial<Record<SatelliteGroup, readonly TleRecord[]>>
}

const typedSnapshot = snapshot as FallbackSnapshot

export function fallbackRecords(group: SatelliteGroup): readonly TleRecord[] {
  return typedSnapshot.groups[group] ?? []
}

export function fallbackGeneratedAt(): string {
  return typedSnapshot.generatedAt
}

/** Age of the stalest element in the bundled snapshot, in hours. */
export function fallbackAgeHours(group: SatelliteGroup, now: Date = new Date()): number {
  return maxEpochAge(fallbackRecords(group), now)
}
